### ISSUE TITLE
Server crash on load - cpw.mods.fml.common.LoaderException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProsperCraft** [Rikmuld/CampingMod-mcmod#18]
http://pastebin.com/z03TQnuz

**Comment by GreatOrator** [comment]
have another example for you:

http://pastebin.com/j6m921Pr

**Comment by Error998** [comment]
The Camping Mod Version: 2.1d
Forge Version: 10.13.2.1236
Minecraft Version: 1.7.10

Tested on Multiplayer

Steps to reproduce issue:
Start server

Occurrence:
Always

Result:
Fatal server crash in server preinitialization
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149708_J()Lnet/minecraft/creativetab/CreativeTabs;

Crash Log:
http://pastebin.com/Wxj10HkB


Please note that the mod loads without errors on the client, seems like it might be a client side only function that is being called server side?
Someone else had something similar: http://www.minecraftforge.net/forum/index.php?topic=8017.0

Thanks for all the hard work Rikmuld!
Loving the mod so far

Error_998

**Comment by Rikmuld** [comment]
Fixed the server error and tent render error.

**Comment by Cozza38** [comment]
Hi Rik,

Any chance we will see this new version soon? As CampingMod has worldgen, if it is removed from the server it causes horrible chunk tearing on new chunks due to the seed change. 

In particular, this is a big issue on modpacks with prebuilt maps like Tolkiencraft where worldgen is broken just outside the spawn region. (see:http://i.imgur.com/edOpnVf.jpg)

If it makes it any easier, I'm happy to offer a Jenkins server for you to quickly compile on in the future.

**Comment by Rikmuld** [comment]
I just updated :)

**Comment by Cozza38** [comment]
Thank you!
