### ISSUE TITLE
Server crash on worldgen

### ISSUE THREAD

**Issue by ProsperCraft** [Rikmuld/CampingMod-mcmod#22]
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:59)

http://pastebin.com/msr5bhjE

**Comment by GreatOrator** [comment]
Have three other crashes related to world gen that may help.

http://pastebin.com/dM7JHriT
http://pastebin.com/1VWsABKa
http://pastebin.com/y247KfBy

**Comment by ProsperCraft** [comment]
This is still happening with TheCampingMod_2.1f

It crashes the whole server.

http://pastebin.com/zmWd5qaQ

**Comment by Rikmuld** [comment]
Sorry for my late response, I was quite busy with some other stuff lately.

About this error: it occurs because the tents in the randomly generated campsites are mostly 'invisible' for the world generation of other mods (most of the tent blocks ar just fillers to get a nice large view/collision bound around the tent). Those 'filler' blocks are getting overridden by non minecraft world gen and that causes the game to crash.

Soon I will have lots of time and then I shall fix it as soon as possible, for now you can fix it by disabling the campsite generation in the config file. Sorry for the inconvenience.

**Comment by Rikmuld** [comment]
Probably fixed, an update will be made available soon.
